/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbDelivery;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.SwingConstants;

/**
 *
 * @author 17jz0101 Lee Ho Jae
 */
public class BoundaryOrderCSlip extends javax.swing.JFrame {
    DefaultListModel     nameListModel = new DefaultListModel();
    DefaultListModel     amountListModel = new DefaultListModel();
    DefaultListModel     priceListModel = new DefaultListModel();
    DefaultListCellRenderer rendar;
    ControlOrderCSlip    control;

    /**
     * Creates new form BoundaryOrderSlip
     */
    public BoundaryOrderCSlip() {
        initComponents();
        setTitle("注文伝票（顧客用）");
        setLocationRelativeTo(this);
        initList();
    }
    
    private void initList() {
        jListOrderCSlipName.setModel(nameListModel);
        jListOrderCSlipAmount.setModel(amountListModel);
        jListOrderCSlipPrice.setModel(priceListModel);
        rendar = new DefaultListCellRenderer();
        rendar.setHorizontalAlignment(SwingConstants.RIGHT);
        jListOrderCSlipName.setCellRenderer(rendar);
        jListOrderCSlipAmount.setCellRenderer(rendar);
        jListOrderCSlipPrice.setCellRenderer(rendar);
    }
    
    public void setForm() {
        int h = 0;
        if(jListOrderCSlipName.getModel().getSize() > 10) {
            h = (jListOrderCSlipName.getModel().getSize() - 10) * 30;
            System.out.println(h);
            this.setSize(this.getWidth(), this.getHeight() + h);            
        } 
    }
    
    public void setControl(ControlOrderCSlip control) {
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelOrderCSName = new javax.swing.JLabel();
        jLabelOrderCSAddress = new javax.swing.JLabel();
        jLabelOrderCSTel = new javax.swing.JLabel();
        jLabelOrderCSPoint = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListOrderCSlipName = new javax.swing.JList<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelOrderCSUsingPoint = new javax.swing.JLabel();
        jLabelOrderCSSubTotalPrice = new javax.swing.JLabel();
        jLabelCSTotalPrice = new javax.swing.JLabel();
        jLabelCSGrantPoint = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListOrderCSlipAmount = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListOrderCSlipPrice = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabelOrderCSOrderDates = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel1.setText("店舗名 ：");

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel2.setText("トリピミックス");

        jLabel3.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel3.setText("住所　：");

        jLabel4.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel4.setText("東京都新宿区百人町1-25-4");

        jSeparator1.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel5.setText("店舗電話　：");

        jLabel6.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel6.setText("03-4515-9788");

        jLabel7.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel7.setText("商品名");

        jLabel8.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel8.setText("数量");

        jLabel9.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabel9.setText("価格");

        jLabelOrderCSName.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelOrderCSName.setText("名前");

        jLabelOrderCSAddress.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelOrderCSAddress.setText("住所");

        jLabelOrderCSTel.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelOrderCSTel.setText("電話番号");

        jLabelOrderCSPoint.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        jLabelOrderCSPoint.setText("ポイント");

        jScrollPane1.setBorder(null);

        jListOrderCSlipName.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9", "Item 10", "Item 11" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListOrderCSlipName);

        jLabelOrderCSUsingPoint.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabelOrderCSUsingPoint.setText("使用ポイント");

        jLabelOrderCSSubTotalPrice.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabelOrderCSSubTotalPrice.setText("小計金額");

        jLabelCSTotalPrice.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabelCSTotalPrice.setText("合計金額");

        jLabelCSGrantPoint.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabelCSGrantPoint.setText("付与ポイント");

        jScrollPane2.setBorder(null);

        jListOrderCSlipAmount.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListOrderCSlipAmount);

        jScrollPane3.setBorder(null);

        jListOrderCSlipPrice.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListOrderCSlipPrice);

        jLabel10.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabel10.setText("注文日　：");

        jLabelOrderCSOrderDates.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        jLabelOrderCSOrderDates.setText("注文日");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabelOrderCSOrderDates)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOrderCSTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelOrderCSPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOrderCSAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelOrderCSName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelOrderCSSubTotalPrice)
                        .addComponent(jLabelCSTotalPrice))
                    .addComponent(jLabelOrderCSUsingPoint)
                    .addComponent(jLabelCSGrantPoint))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelOrderCSOrderDates))
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOrderCSUsingPoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOrderCSSubTotalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCSTotalPrice)
                .addGap(9, 9, 9)
                .addComponent(jLabelCSGrantPoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOrderCSName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOrderCSAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOrderCSTel)
                .addGap(10, 10, 10)
                .addComponent(jLabelOrderCSPoint)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        control.showOrderCSlipView();
        setForm();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        control.showOrderReception();
    }//GEN-LAST:event_formWindowClosing

    public void setInformationCustomerSlip(String name, String tel, String address, int point, Timestamp orderDates) {
        jLabelOrderCSName.setText("顧客名   : " + name + " 様");
        jLabelOrderCSTel.setText("電話番号  : " + tel);
        jLabelOrderCSAddress.setText("住所  : " + address);
        jLabelOrderCSPoint.setText("ポイント残高  : " + Integer.toString(point));
        jLabelOrderCSOrderDates.setText(orderDates.toString());
    }
    
    public void setInformationOrderPriceSlip(int usingPoint, int subTotalPrice, int totalPrice, int grantPoint) {
        jLabelOrderCSUsingPoint.setText("使用ポイント : " + Integer.toString(usingPoint));
        jLabelOrderCSSubTotalPrice.setText("注文小計金額 : " + "\\ " + Integer.toString(subTotalPrice));
        jLabelCSTotalPrice.setText("注文合計金額 : " + "\\ " + Integer.toString(totalPrice));
        jLabelCSGrantPoint.setText("付与ポイント : " + Integer.toString(grantPoint));
    }
    
    public void addListOrderCSlipName(String[] rowData) {
        for(String data : rowData) {
            nameListModel.addElement(data);
        }
    }
    
    public void addListOrderCSlipCount(String[] rowData) {
        for(String data : rowData) {
            amountListModel.addElement(data);
        }
    }

    public void addListOrderCSlipPrice(String[] rowData) {
        for(String data : rowData) {
            priceListModel.addElement("¥ " + data);
        }
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoundaryOrderCSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoundaryOrderCSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoundaryOrderCSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoundaryOrderCSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoundaryOrderCSlip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCSGrantPoint;
    private javax.swing.JLabel jLabelCSTotalPrice;
    private javax.swing.JLabel jLabelOrderCSAddress;
    private javax.swing.JLabel jLabelOrderCSName;
    private javax.swing.JLabel jLabelOrderCSOrderDates;
    private javax.swing.JLabel jLabelOrderCSPoint;
    private javax.swing.JLabel jLabelOrderCSSubTotalPrice;
    private javax.swing.JLabel jLabelOrderCSTel;
    private javax.swing.JLabel jLabelOrderCSUsingPoint;
    private javax.swing.JList<String> jListOrderCSlipAmount;
    private javax.swing.JList<String> jListOrderCSlipName;
    private javax.swing.JList<String> jListOrderCSlipPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
