/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  17jz0101 Lee Ho Jae
 * Created: 2018/11/29
 */

INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A01', 'トリピミックス', 2500);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A02', 'ベーコンピザ', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A03', 'マルゲリータピザ', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A04', 'オリーブピザ', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A05', 'アンチョビピザ', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A06', 'クアトロ・スタジオーニピザ', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A07', 'フライドチキン', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A08', 'しょう油チキン', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A09', 'チリチキン', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A10', 'カルビーチキン', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A11', 'チーズチキン', 1200);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A12', '半々チキン', 1350);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A13', '半々ピザ', 1350);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A14', 'コーラ', 400);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A15', 'スプライト', 400);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A16', '(S)コーラ', 0);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A17', '(S)スプライト', 0);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A18', '(S)トリピミックス', 0);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A19', '(S)ミニチキン', 0);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A20', '(S)ミニピザ', 0);
INSERT INTO ITEM (ITEM_ID, ITEM_NAME, ITEM_PRICE) VALUES ('A21', '10%割引', 0);
