/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  17jz0101 Lee Ho Jae
 * Created: 2018/11/29
 */

INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (1, 'A01', 10001, 1, 2500);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (2, 'A16', 10001, 1, 0);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (3, 'A01', 10002, 1, 2500);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (4, 'A16', 10002, 1, 0);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (5, 'A01', 10003, 1, 2500);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (6, 'A17', 10003, 1, 0);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (7, 'A01', 10004, 1, 2500);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (8, 'A17', 10004, 1, 0);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (9, 'A01', 10005, 1, 2500);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (10, 'A17', 10005, 1, 0);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (11, 'A01', 10006, 1, 2500);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (12, 'A16', 10006, 1, 0);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (13, 'A15', 10006, 1, 400);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (14, 'A02', 10007, 1, 1200);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (15, 'A15', 10007, 1, 400);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (16, 'A12', 10008, 1, 1350);
INSERT INTO ORDERDETAIL (ORDERDETAIL_ID, ITEM_ID, ORDER_ID, ORDERCOUNT, ORDERPRICE) VALUES (17, 'A14', 10008, 1, 400);



